abstract class DailyMissionsStates{}
class DMInitState extends DailyMissionsStates{}
class OnSetTimeButtonTappedState extends DailyMissionsStates{}
class OnSetDateButtonTappedState extends DailyMissionsStates{}
class OnBottomSheetDoneButtonTappedState extends DailyMissionsStates{}